/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author ISTA
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form ventana_inicio
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("ACADEMIA MUSICAL REDNOTE");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuProfesor = new javax.swing.JMenu();
        MenuAlumno = new javax.swing.JMenu();
        MenuAdmin = new javax.swing.JMenu();
        MenuContactos = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Portada.png"))); // NOI18N
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        MenuProfesor.setText("Profesor");
        MenuProfesor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuProfesor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuProfesorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuProfesorMouseEntered(evt);
            }
        });
        jMenuBar1.add(MenuProfesor);

        MenuAlumno.setText("Alumno");
        MenuAlumno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuAlumnoMouseEntered(evt);
            }
        });
        jMenuBar1.add(MenuAlumno);

        MenuAdmin.setText("Administrador");
        MenuAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuAdminMouseEntered(evt);
            }
        });
        jMenuBar1.add(MenuAdmin);

        MenuContactos.setText("Contactos");
        MenuContactos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MenuContactosMouseEntered(evt);
            }
        });
        jMenuBar1.add(MenuContactos);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuProfesorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProfesorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuProfesorMouseClicked

    private void MenuAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdminMouseClicked
        Inicio_admin inicio_admin = new Inicio_admin();
        inicio_admin.setVisible(true);
    }//GEN-LAST:event_MenuAdminMouseClicked

    private void MenuProfesorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuProfesorMouseEntered
       MenuProfesor.setBackground(new Color(164,164,164));
    }//GEN-LAST:event_MenuProfesorMouseEntered

    private void MenuAlumnoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAlumnoMouseEntered
       MenuAlumno.setBackground(new Color(164,164,164));
    }//GEN-LAST:event_MenuAlumnoMouseEntered

    private void MenuAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdminMouseEntered
       MenuAdmin.setBackground(new Color(164,164,164));
    }//GEN-LAST:event_MenuAdminMouseEntered

    private void MenuContactosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuContactosMouseEntered
       MenuContactos.setBackground(new Color(164,164,164));
    }//GEN-LAST:event_MenuContactosMouseEntered
 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdmin;
    private javax.swing.JMenu MenuAlumno;
    private javax.swing.JMenu MenuContactos;
    private javax.swing.JMenu MenuProfesor;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
