/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Modelo.*;
import com.db4o.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class OpcionesCursos extends javax.swing.JFrame {

    Validaciones vali = new Validaciones();
    private String id, nombre, fechaini, fechafin, precio;
    private boolean validar;

    public OpcionesCursos() {
        initComponents();
        mostrarTabla();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de curso");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        BtnRegistrocurso = new javax.swing.JButton();
        btnModcurso = new javax.swing.JButton();
        BtnEliminCurso = new javax.swing.JButton();
        btnBuscarC = new javax.swing.JButton();
        txtrgtroAlumno = new javax.swing.JLabel();
        txtprecio = new javax.swing.JTextField();
        txtidcurso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaRgtrcurso = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fecha_ini = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        fecha_fina = new com.toedter.calendar.JDateChooser();
        BtnRegresarRegresar = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnRegistrocurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnRegistrocurso.setText("REGISTRAR");
        BtnRegistrocurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrocursoActionPerformed(evt);
            }
        });

        btnModcurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnModcurso.setText("MODIFICAR");
        btnModcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModcursoActionPerformed(evt);
            }
        });

        BtnEliminCurso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BtnEliminCurso.setText("ELIMINAR");
        BtnEliminCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminCursoActionPerformed(evt);
            }
        });

        btnBuscarC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBuscarC.setText("BUSCAR");
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnRegistrocurso)
                    .addComponent(btnModcurso)
                    .addComponent(BtnEliminCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(BtnRegistrocurso)
                .addGap(28, 28, 28)
                .addComponent(btnModcurso)
                .addGap(34, 34, 34)
                .addComponent(BtnEliminCurso)
                .addGap(34, 34, 34)
                .addComponent(btnBuscarC)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        txtrgtroAlumno.setFont(new java.awt.Font("Papyrus", 2, 24)); // NOI18N
        txtrgtroAlumno.setText("Registro de Cursos");

        txtidcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidcursoActionPerformed(evt);
            }
        });

        TablaRgtrcurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Fecha de inicio", "Fecha de fin", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TablaRgtrcurso);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("$");

        jLabel2.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabel2.setText("Id");

        jLabel3.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabel4.setText("Fecha de inicio");

        jLabel5.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabel5.setText("Fecha de Fin");

        jLabel7.setFont(new java.awt.Font("Roboto Thin", 1, 18)); // NOI18N
        jLabel7.setText("Precio ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        BtnRegresarRegresar.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        BtnRegresarRegresar.setText("REGRESAR");
        BtnRegresarRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_ini, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha_fina, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(txtrgtroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnRegresarRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtrgtroAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(fecha_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(fecha_fina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(BtnRegresarRegresar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminCursoActionPerformed

    private void BtnRegresarRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarRegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnRegresarRegresarActionPerformed

    private void txtidcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidcursoActionPerformed

    private void BtnRegistrocursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrocursoActionPerformed
        ObjectContainer BaseBD = Conexion.ConectarBD();
        if (txtidcurso.getText().equals("") || txtnombre.getText().equals("") || (fecha_ini.getDate().toString()).equals("") || (fecha_fina.getDate().toString()).equals("")
                || txtprecio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        } else {
            id = txtidcurso.getText().trim();
            nombre = txtnombre.getText().trim();
            fechaini = (fecha_ini.getDate().toString());
            fechafin = (fecha_fina.getDate().toString());
            precio = txtprecio.getText().trim();
            Cursos curso = new Cursos(id, nombre, fechaini, fechafin, precio);
            if (Validar_Curso(BaseBD, id) == 0) {
                if (vali.Validarcodigo(id)) {
                    if (vali.Validarnombrec(nombre)) {
                        if (vali.Validarprecio(precio)) {
                            BaseBD.set(curso);
                            JOptionPane.showMessageDialog(null, "El curso fue guardado exitosamente!");
                            limpiarLabel();
                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese el precio correcto, min 30 max 150 !!");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Nombre incorrecto ingrese nuevamente!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "ID incorrecto ingrese nuevamente!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "El cliente ya existe, no se puede registrar");
            }
            BaseBD.close();
            mostrarTabla();
        }
    }//GEN-LAST:event_BtnRegistrocursoActionPerformed

    private void btnModcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModcursoActionPerformed
        ObjectContainer BaseBD = Conexion.ConectarBD();
        String idcurso = JOptionPane.showInputDialog("Ingrese el id del curso que desea Modificar: ");
        id = idcurso;
        Cursos Cbuscar = new Cursos(id, null, null, null, null);
        ObjectSet resul = BaseBD.get(Cbuscar);
        if (validar_cursoc(BaseBD, id)) {
            txtidcurso.setText(idcurso);
            txtidcurso.setEnabled(false);
            Cursos cursom = (Cursos) resul.next();
            String nomc = JOptionPane.showInputDialog("Ingrese el nombre del curso");
            txtnombre.setText(nomc.toUpperCase().trim());
            String fechain = JOptionPane.showInputDialog("Ingrese la fecha de inicio del curso");
            fecha_ini.getDateFormatString();
            String fechafin = JOptionPane.showInputDialog("Ingrese la fecha de fin del curso");
            fecha_fina.getDate().toString();
            String precioc = JOptionPane.showInputDialog("Ingrese el precio del curso");
            txtprecio.setText(precioc.toUpperCase().trim());

            cursom.setNombre_curso(nomc);
            cursom.setFecha_ini(fechain);
            cursom.setFecha_fin(fechafin);
            cursom.setPrecio(precioc);

            JOptionPane.showMessageDialog(null, "¡El curso ha sido modificado con exito!");
            BaseBD.set(cursom);
        } else {
            JOptionPane.showMessageDialog(null, "¡El curso no está registrado en la base de datos!");
        }
        txtidcurso.setEnabled(true);
        limpiarLabel();
        BaseBD.close();
        mostrarTabla();

    }//GEN-LAST:event_btnModcursoActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed
        ObjectContainer BaseBD = Conexion.ConectarBD();
        String idcu = JOptionPane.showInputDialog(null, "Ingrese el id del curso que desa buscar ");
        id = idcu;
        Cursos Cbuscar = new Cursos(id, null, null, null, null);
        ObjectSet resul = BaseBD.get(Cbuscar);

        if (validar_cursoc(BaseBD, id)) {

            Consultar_Curso_Parametro(BaseBD, id);

        } else {
            JOptionPane.showMessageDialog(null, "¡El Alumno no está registrado en la base de datos!");
        }

        BaseBD.close();

    }//GEN-LAST:event_btnBuscarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OpcionesCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OpcionesCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OpcionesCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OpcionesCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OpcionesCursos().setVisible(true);
            }
        });
    }

    public void limpiarLabel() {
        txtidcurso.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
    }

    public static void Consultar_Curso_Parametro(ObjectContainer base, String id) {

        Cursos Cbuscar = new Cursos(id, null, null, null, null);
        ObjectSet resul = base.get(Cbuscar);
        JOptionPane.showMessageDialog(null, "Existen " + resul.size() + " cursos");

    }

    public static int Validar_Curso(ObjectContainer BaseBD, String id) {

        Cursos Cbuscar = new Cursos(id, null, null, null, null);

        ObjectSet resul = BaseBD.get(Cbuscar);
        return resul.size();
    }

    public boolean validar_cursoc(ObjectContainer BaseBD, String id) {

        Cursos Vcurso = new Cursos(id, null, null, null, null);

        ObjectSet resul = BaseBD.get(Vcurso);

        validar = resul.hasNext();
        return validar;
    }

    public void mostrarTabla() {

        ObjectContainer BaseBD = Conexion.ConectarBD();
        Cursos Tcurso = new Cursos(null, null, null, null, null);
        ObjectSet resul = BaseBD.get(Tcurso);

        String matriz[][] = new String[resul.size()][5];

        for (int i = 0; i < resul.size(); i++) {
            Cursos cursoG = (Cursos) resul.next();
            matriz[i][0] = cursoG.getId_curso();
            matriz[i][1] = cursoG.getNombre_curso().toUpperCase();
            matriz[i][2] = cursoG.getFecha_ini().toUpperCase();
            matriz[i][3] = cursoG.getFecha_fin();
            matriz[i][4] = cursoG.getPrecio();
        }
        TablaRgtrcurso.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Id", "Nombre", "Fecha inicio", "Fecha fin", "precio"
                }
        ));
        BaseBD.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminCurso;
    private javax.swing.JButton BtnRegistrocurso;
    private javax.swing.JButton BtnRegresarRegresar;
    private javax.swing.JTable TablaRgtrcurso;
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JButton btnModcurso;
    private com.toedter.calendar.JDateChooser fecha_fina;
    private com.toedter.calendar.JDateChooser fecha_ini;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtidcurso;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JLabel txtrgtroAlumno;
    // End of variables declaration//GEN-END:variables
}
